import Hero from "@/components/Hero";
import Slider from "@/components/Slider";
import Head from "next/head";
import Image from "next/image";
import { SliderData } from "@/components/SliderData";
import Instagram from "@/components/Instagram";

export default function Home() {
  return (
    <>
      <Head>
        <title>Teda NGO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Hero
        heading={"Teda NGO"}
        message={"We are a non-profit organization that helps people in need."}
      />
      <Slider slides={SliderData} />
      <Instagram />
    </>
  );
}
