import Hero from "@/components/Hero";
import Slider from "@/components/Slider";
import Head from "next/head";
import Image from "next/image";
import { SliderData } from "@/components/SliderData";
import Instagram from "@/components/Instagram";
import Values from "@/components/Values";
import Footer from "@/components/Footer";

export default function Home() {
  return (
    <>
      <Head>
        <title>Teda NGO</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Slider slides={SliderData} />
      <Values />
      <Footer />
    </>
  );
}
